

FROM rocker/rstudio:latest

# Install latest version of R
RUN apt-get update && \
    apt-get install -y r-base && \
    rm -rf /var/lib/apt/lists/*


#OS level prereq pacakges
RUN apt-get update 
RUN apt-get install -y libxml2 libglpk-dev libxml2-dev libhdf5-dev libbz2-dev  libhdf5-dev zlib1g-dev libcurl4-gnutls-dev libssl-dev libz-dev libudunits2-dev gdal-bin


#Install tidyverse and vizu tool
RUN Rscript -e 'install.packages("tidyverse")'
RUN Rscript -e 'install.packages("plotly")'
RUN Rscript -e "install.packages('DT')"
RUN Rscript -e "tinytex::install_tinytex()"
#Install managers
RUN Rscript -e 'install.packages("devtools")' \
	&& Rscript -e 'install.packages("BiocManager")'


#BiocManager prereq installs for CellChat
RUN Rscript -e 'BiocManager::install("ComplexHeatmap")' \
	&& Rscript -e 'BiocManager::install("BiocGenerics")' \
	&& Rscript -e 'BiocManager::install("Biobase")'\
	&& Rscript -e 'BiocManager::install("BiocNeighbors")'\
	&& Rscript -e 'BiocManager::install("remotes")'\
	&& Rscript -e 'BiocManager::install("celldex")'\
	&& Rscript -e 'devtools::install_github(repo = "hhoeflin/hdf5r")'\
	&& Rscript -e 'devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")'\
	&& Rscript -e 'remotes::install_github("mojaveazure/seurat-disk")'\
	&& Rscript -e 'BiocManager::install("AnnotationDbi", force = T)'\
	&& Rscript -e "devtools::install_github('satijalab/seurat-data')"\
	&& Rscript -e 'remotes::install_github("mojaveazure/seurat-disk")'


#Github prereq installs for CellChat
RUN Rscript -e 'Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE); devtools::install_github("renozao/NMF")' \
	&& Rscript -e 'devtools::install_github("jokergoo/circlize")'

#CellChat install
RUN Rscript -e 'remotes::install_github("sqjin/CellChat")'

#Packages supporting Shiny and graphics
RUN Rscript -e 'install.packages(c("shinyWidgets", "shinythemes", "ggplot2", "ggalluvial", "shinyjs", "shinycssloaders", "dplyr"))'
RUN Rscript -e 'install.packages( "Seurat")'

RUN apt-get update && apt-get install -y samtools

RUN apt-get update && apt-get install -y libbz2-dev 

RUN R -e 'install.packages("Rhtslib", repos = "https://cran.r-project.org")'
RUN R -e "install.packages(c('cluster', 'MASS', 'Matrix', 'mgcv', 'nlme', 'survival'), repos='https://cran.r-project.org/')"
RUN R -e "install.packages('Rhtslib', dependencies = TRUE, repos='http://cran.rstudio.com/')"
# converte matrix feature count to table count
RUN Rscript -e 'BiocManager::install("GenomicFeatures")'\
	&& Rscript -e 'BiocManager::install("Rsamtools")'\
	&& Rscript -e 'BiocManager::install("tximport")'\
	&& Rscript -e 'BiocManager::install("org.Mm.eg.db")'\
	&& Rscript -e 'BiocManager::install("granulator")'\
	&& Rscript -e 'BiocManager::install("rhdf5")'\
	&& Rscript -e 'BiocManager::install("limma")'

RUN rm -Rf /srv/shiny-server/*